# Prompt
cd ~/dev/env/bash && . prompt.sh

# Environment variables
export PATH="/usr/local/bin:$HOME/bin:$PATH"
export MANPATH="/opt/local/man:$MANPATH"
export EDITOR="which mate"

# python
export PATH="/Library/Frameworks/Python.framework/Versions/3.3/bin:$PATH"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# DOS commands, I just can't quit you!
alias dir="ls -lFah"
alias md="mkdir"
alias rd="rm -rf"
alias cd..="cd .."
alias cls="clear"

# Tricks I picked up along the way
alias ll="ls -lFh"
alias lla="ls -lFah"
alias edit="mate"
alias iphone="open -a iPhone\ Simulator"
alias be="bundle exec"
alias cucumber="bundle exec cucumber"
alias py="python3.3"
alias pg="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log"


# Display folder and it's content as a tree
function tree {
 find ${1:-.} -print | sed -e 's;[^/]*/;|__;g;s;__|; |;g'
}

# Source the git completion script
source ~/dev/env/git/git-completion.bash

# Return to development directory
cd ~/dev
