# Prompt
cd ~/dev/env/bash && . prompt.sh 

# Environment variables
export PATH="/usr/local/bin:$HOME/bin:$PATH" 
export MANPATH="/opt/local/man:$MANPATH"
export EDITOR="which mate"

# python
export PATH="/Library/Frameworks/Python.framework/Versions/3.3/bin:$PATH" 

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH" 
eval "$(rbenv init -)"

# DOS commands, I just can't quit you!
alias dir="ls -lFah"
alias md="mkdir"
alias rd="rm -rf"
alias cd..="cd .."
alias cls="clear"

# Tricks I picked up along the way
alias ll="ls -lFh"
alias lla="ls -lFah"
alias edit="mate"
alias iphone="open -a iPhone\ Simulator"
alias be="bundle exec"
alias py="python3.3"

# Display folder and it's content as a tree
function tree {
 find ${1:-.} -print | sed -e 's;[^/]*/;|__;g;s;__|; |;g'
}

# Return to development directory
cd ~/dev

