# SSH Keys
ssh-add ~/.ssh/id_rsa

# Prompt
cd ~/dev/env/bash && . prompt.sh

# Environment variables
export PATH="$HOME/bin:$PATH"
export MANPATH="/opt/local/man:$MANPATH"
export EDITOR="atom"

# python
export PATH="~/Library/Python/2.7/bin:$PATH"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# DOS commands, I just can't quit you!
alias dir="ls -lFah"
alias rd="rm -rf"
alias cd..="cd .."
alias cls="clear"

# Tricks I picked up along the way
alias ll="ls -lFh"
alias lla="ls -lFah"
alias edit="mate"
alias iphone="open -a iPhone\ Simulator"
alias be="bundle exec"
alias bs="bundle exec spring"
alias cucumber="bundle exec cucumber"

# MKDIR the way it should be
md() {
  mkdir $1
  cd $1
}

# Display folder and it's content as a tree
function tree {
 find ${1:-.} -print | sed -e 's;[^/]*/;|__;g;s;__|; |;g'
}

# Source the git completion script
source ~/dev/env/git/git-completion.bash

# Return to development directory
cd ~/dev
